---
name: 'Setup Yorick'
author: Yevhen Fabizhevskyi
description: 'This action installs yorick.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'yorick version.'
    required: false
    default: '2.2.04'
runs:
  using: 'composite'
  steps:
    - name: Fail
      uses: actions/github-script@v6
      if: ${{ runner.os == 'Windows' }}
      with:
        script: core.setFailed('${{ runner.os }} ${{ runner.arch }} is not supported');
    - name: Build version
      id: version
      if: ${{ runner.os != 'Windows' }}
      uses: actions/github-script@v6
      with:
        script: |
          const a = '${{ inputs.version }}'.split('.');
          return `y_${a[0]}_${a[1]}_${a[2]}`;
    - name: Collect info
      id: info
      if: ${{ runner.os != 'Windows' }}
      run: |
        YORICK_INSTALLED=$(if command -v yorick >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "YORICK_INSTALLED=$YORICK_INSTALLED" >> $GITHUB_OUTPUT
        mkdir -p "$GITHUB_WORKSPACE/yorick"
        echo "YORICK_PATH=$GITHUB_WORKSPACE/yorick" >> $GITHUB_OUTPUT
        echo "YORICK_VERSION=${{ steps.version.outputs.result }}" >> $GITHUB_OUTPUT
      shell: sh
    - name: Download yorick
      if: ${{ runner.os != 'Windows' && steps.info.outputs.YORICK_INSTALLED == 'false' }}
      uses: actions/checkout@v3
      with:
        repository: LLNL/yorick
        ref: ${{ steps.info.outputs.YORICK_VERSION }}
        fetch-depth: 1
        path: yorick
    - name: Install yorick
      if: ${{ runner.os != 'Windows' && steps.info.outputs.YORICK_INSTALLED == 'false' }}
      run: |
        make install
        echo "${{ steps.info.outputs.YORICK_PATH }}/relocate/bin" >> $GITHUB_PATH
      shell: sh
      working-directory: ${{ steps.info.outputs.YORICK_PATH }}
