---
name: 'Setup Yorick'
author: Yevhen Fabizhevskyi
description: 'This action installs yorick.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'yorick version.'
    required: false
    default: 'y_2_2_04'
runs:
  using: 'composite'
  steps:
    - name: Collect info
      id: info
      run: |
        YORICK_INSTALLED=$(if command -v yorick >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "YORICK_INSTALLED=$YORICK_INSTALLED" >> $GITHUB_OUTPUT
        mkdir -p "$GITHUB_WORKSPACE/yorick"
        echo "YORICK_PATH=$GITHUB_WORKSPACE/yorick" >> $GITHUB_OUTPUT
      shell: bash
    - name: Download yorick
      if: ${{ steps.info.outputs.YORICK_INSTALLED == 'false' }}
      uses: actions/checkout@v3
      with:
        repository: LLNL/yorick
        ref: ${{ inputs.version }}
        fetch-depth: 1
        path: yorick
    - name: Install yorick
      run: |
        make install
        echo "${{ steps.info.outputs.YORICK_PATH }}/relocate/bin" >> $GITHUB_PATH
      shell: bash
      working-directory: ${{ steps.info.outputs.YORICK_PATH }}
