---
name: "Setup Yorick"
author: Yevhen Fabizhevskyi
description: "This action installs yorick."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "yorick version."
    required: false
    default: "2.2.04"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'Windows' }}
      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
      shell: sh
    - name: Build version
      id: version
      env:
        INPUT_VERSION: "${{ inputs.version }}"
      run: |
        major="$(echo "${INPUT_VERSION}" | cut -d. -f1)"
        minor="$(echo "${INPUT_VERSION}" | cut -d. -f2)"
        patch="$(echo "${INPUT_VERSION}" | cut -d. -f3)"
        echo "result=y_${major}_${minor}_${patch}" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Collect info
      id: info
      run: |
        YORICK_INSTALLED=$(if command -v yorick >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "YORICK_INSTALLED=$YORICK_INSTALLED" >> $GITHUB_OUTPUT
        mkdir -p "$GITHUB_WORKSPACE/yorick"
        echo "YORICK_PATH=$GITHUB_WORKSPACE/yorick" >> $GITHUB_OUTPUT
        echo "YORICK_VERSION=${{ steps.version.outputs.result }}" >> $GITHUB_OUTPUT
      shell: sh
    - name: Download yorick
      if: ${{ steps.info.outputs.YORICK_INSTALLED == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: LLNL/yorick
        ref: ${{ steps.info.outputs.YORICK_VERSION }}
        fetch-depth: 1
        path: yorick
    - name: Install yorick
      if: ${{ steps.info.outputs.YORICK_INSTALLED == 'false' }}
      run: |
        make install
        echo "${{ steps.info.outputs.YORICK_PATH }}/relocate/bin" >> $GITHUB_PATH
      shell: sh
      working-directory: ${{ steps.info.outputs.YORICK_PATH }}
