---
name: Functional Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  setup-yorick:
    name: Setup yorick
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        version: ['2.2.04', '2.2.03', '2.2.02']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yorick
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: yorick --version
        shell: sh
