---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: sh

jobs:
  setup-yorick:
    name: Setup yorick
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
        version: ["2.2.04", "2.2.03", "2.2.02"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Yorick
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: yorick --version
