---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - "main"

defaults:
  run:
    shell: sh

jobs:
  setup-yorick:
    name: Setup yorick
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        runner: ["ubuntu-latest", "macos-12"]
        version: ["2.2.04", "2.2.03", "2.2.02"]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup Yorick
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: yorick --version
